'use strict';

const ActionTypes = {
    GET_USERS: 'GET_USERS',
    GET_ORDER_TYPES: 'GET_ORDER_TYPES',
    GET_SORTABLE_FIELDS: 'GET_SORTABLE_FIELDS',
    FILTER_USERS: 'FILTER_USERS',
    SORT_USERS: 'SORT_USERS',
    SET_ACTIVE_USER: 'SET_ACTIVE_USER'
};

export default ActionTypes;